import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/redux/provider";
import { NavBar } from "@/components/main-components/NavBar";
import AuthStateLoader from "@/redux/AuthStateLoader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <div
          className="bg-orange-100 sm:mt-20 absolute top-[-6rem] -z-10 sm:left-[45rem]
         sm:h-[40.25rem] sm:w-[70rem] rounded-full blur-[10rem] 
         "
        ></div>
        <ReduxProvider>
          <AuthStateLoader>
            <NavBar />
            {children}
          </AuthStateLoader>
        </ReduxProvider>
      </body>
    </html>
  );
}
